# Default values for druid-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env:
  DENY_LIST: "default,kube-system" # Comma-separated list of namespaces to ignore
  RECONCILE_WAIT: "10s"            # Reconciliation delay
  WATCH_NAMESPACE: ""              # Namespace to watch or empty string to watch all namespaces, To watch multiple namespaces add , into string. Ex: WATCH_NAMESPACE: "ns1,ns2,ns3"
  #MAX_CONCURRENT_RECONCILES:: ""  # MaxConcurrentReconciles is the maximum number of concurrent Reconciles which can be run.

replicaCount: 1

image:
  repository: datainfrahq/druid-operator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

livenessProbe: {}
  # httpGet:
  #   path: /healthz
  #   port: 8081
  # initialDelaySeconds: 15
  # periodSeconds: 20

readinessProbe: {}
  # httpGet:
  #   path: /readyz
  #   port: 8081
  # initialDelaySeconds: 5
  # periodSeconds: 10

rbac:
  create: true

serviceAccount:
  # Annotations to add to the service account
  annotations:
    kubectl.kubernetes.io/default-container: manager
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "druid-operator-controller-manager"

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

crd:
  enabled: true
