name: druid-operator
lang: golang
lang_version: 1.20.6
git:
  enable: true
github:
  enable: true
  repo_name: confluentinc/druid-operator
semaphore:
  enable: true
  pipeline_enable: false
  triggers:
  - branches
  - pull_requests
  branches:
  - master
  - cc-druid-operator
