name: druid-operator
lang: unknown
lang_version: unknown
git:
  enable: true
github:
  enable: true
  repo_name: confluentinc/druid-operator
semaphore:
  enable: true
  pipeline_enable: false
  triggers: []
  branches: []
