# permissions for end users to view localstorages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: localstorage-viewer-role
rules:
- apiGroups:
  - storage.confluent.io.apache.org
  resources:
  - localstorages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.confluent.io.apache.org
  resources:
  - localstorages/status
  verbs:
  - get
