kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: druid-operator
subjects:
- kind: ServiceAccount
  name: druid-operator
  namespace: sada-test
roleRef:
  kind: Role
  name: druid-operator
  apiGroup: rbac.authorization.k8s.io
