apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: druid-operator
  namespace: sada-test
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - services
      - persistentvolumeclaims
    verbs:
      - list
      - watch
      - create
      - update
      - delete
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - apps
    resources:
      - statefulsets
      - deployments
      - daemonsets
    verbs:
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - list
      - watch
      - create
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - list
      - watch
      - create
      - update
  - apiGroups:
      - druid.apache.org
      - storage.confluent.io.apache.org
    resources:
      - druids
      - localstorages
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - druid.apache.org
      - storage.confluent.io.apache.org
    resources:
      - druids/status
      - localstorages/status
    verbs:
      - get
      - update
      - patch
