apiVersion: storage.confluent.io.apache.org/v1
kind: LocalStorage
metadata:
  name: localstorage-sample
  namespace: sada-test
spec:
  name: test-localstorage
  replicas: 1
  instanceType: i3.large
  forceDeploy: false 
